// Generated by gencpp from file flyinglightspeck/ReadFLS.msg
// DO NOT EDIT!


#ifndef FLYINGLIGHTSPECK_MESSAGE_READFLS_H
#define FLYINGLIGHTSPECK_MESSAGE_READFLS_H

#include <ros/service_traits.h>


#include <flyinglightspeck/ReadFLSRequest.h>
#include <flyinglightspeck/ReadFLSResponse.h>


namespace flyinglightspeck
{

struct ReadFLS
{

typedef ReadFLSRequest Request;
typedef ReadFLSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadFLS
} // namespace flyinglightspeck


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flyinglightspeck::ReadFLS > {
  static const char* value()
  {
    return "671f8e4998eaec79f1c47e339dfd527b";
  }

  static const char* value(const ::flyinglightspeck::ReadFLS&) { return value(); }
};

template<>
struct DataType< ::flyinglightspeck::ReadFLS > {
  static const char* value()
  {
    return "flyinglightspeck/ReadFLS";
  }

  static const char* value(const ::flyinglightspeck::ReadFLS&) { return value(); }
};


// service_traits::MD5Sum< ::flyinglightspeck::ReadFLSRequest> should match
// service_traits::MD5Sum< ::flyinglightspeck::ReadFLS >
template<>
struct MD5Sum< ::flyinglightspeck::ReadFLSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flyinglightspeck::ReadFLS >::value();
  }
  static const char* value(const ::flyinglightspeck::ReadFLSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flyinglightspeck::ReadFLSRequest> should match
// service_traits::DataType< ::flyinglightspeck::ReadFLS >
template<>
struct DataType< ::flyinglightspeck::ReadFLSRequest>
{
  static const char* value()
  {
    return DataType< ::flyinglightspeck::ReadFLS >::value();
  }
  static const char* value(const ::flyinglightspeck::ReadFLSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flyinglightspeck::ReadFLSResponse> should match
// service_traits::MD5Sum< ::flyinglightspeck::ReadFLS >
template<>
struct MD5Sum< ::flyinglightspeck::ReadFLSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flyinglightspeck::ReadFLS >::value();
  }
  static const char* value(const ::flyinglightspeck::ReadFLSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flyinglightspeck::ReadFLSResponse> should match
// service_traits::DataType< ::flyinglightspeck::ReadFLS >
template<>
struct DataType< ::flyinglightspeck::ReadFLSResponse>
{
  static const char* value()
  {
    return DataType< ::flyinglightspeck::ReadFLS >::value();
  }
  static const char* value(const ::flyinglightspeck::ReadFLSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLYINGLIGHTSPECK_MESSAGE_READFLS_H
