// Generated by gencpp from file flyinglightspeck/fls.msg
// DO NOT EDIT!


#ifndef FLYINGLIGHTSPECK_MESSAGE_FLS_H
#define FLYINGLIGHTSPECK_MESSAGE_FLS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace flyinglightspeck
{
template <class ContainerAllocator>
struct fls_
{
  typedef fls_<ContainerAllocator> Type;

  fls_()
    : header()
    , whatispresent()
    , coordinate()
    , color()
    , duration()  {
    }
  fls_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , whatispresent(_alloc)
    , coordinate(_alloc)
    , color(_alloc)
    , duration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _whatispresent_type;
  _whatispresent_type whatispresent;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _coordinate_type;
  _coordinate_type coordinate;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _color_type;
  _color_type color;

   typedef std::vector<ros::Time, typename ContainerAllocator::template rebind<ros::Time>::other >  _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::flyinglightspeck::fls_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flyinglightspeck::fls_<ContainerAllocator> const> ConstPtr;

}; // struct fls_

typedef ::flyinglightspeck::fls_<std::allocator<void> > fls;

typedef boost::shared_ptr< ::flyinglightspeck::fls > flsPtr;
typedef boost::shared_ptr< ::flyinglightspeck::fls const> flsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flyinglightspeck::fls_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flyinglightspeck::fls_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flyinglightspeck::fls_<ContainerAllocator1> & lhs, const ::flyinglightspeck::fls_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.whatispresent == rhs.whatispresent &&
    lhs.coordinate == rhs.coordinate &&
    lhs.color == rhs.color &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flyinglightspeck::fls_<ContainerAllocator1> & lhs, const ::flyinglightspeck::fls_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flyinglightspeck

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flyinglightspeck::fls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyinglightspeck::fls_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyinglightspeck::fls_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyinglightspeck::fls_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyinglightspeck::fls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyinglightspeck::fls_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flyinglightspeck::fls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07070340d805ea1a3fe23c4fcaeccdf4";
  }

  static const char* value(const ::flyinglightspeck::fls_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07070340d805ea1aULL;
  static const uint64_t static_value2 = 0x3fe23c4fcaeccdf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::flyinglightspeck::fls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flyinglightspeck/fls";
  }

  static const char* value(const ::flyinglightspeck::fls_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flyinglightspeck::fls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8[] whatispresent\n"
"float32[] coordinate\n"
"int8[] color\n"
"time[] duration\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::flyinglightspeck::fls_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flyinglightspeck::fls_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.whatispresent);
      stream.next(m.coordinate);
      stream.next(m.color);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fls_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flyinglightspeck::fls_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flyinglightspeck::fls_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "whatispresent[]" << std::endl;
    for (size_t i = 0; i < v.whatispresent.size(); ++i)
    {
      s << indent << "  whatispresent[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.whatispresent[i]);
    }
    s << indent << "coordinate[]" << std::endl;
    for (size_t i = 0; i < v.coordinate.size(); ++i)
    {
      s << indent << "  coordinate[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coordinate[i]);
    }
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.color[i]);
    }
    s << indent << "duration[]" << std::endl;
    for (size_t i = 0; i < v.duration.size(); ++i)
    {
      s << indent << "  duration[" << i << "]: ";
      Printer<ros::Time>::stream(s, indent + "  ", v.duration[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLYINGLIGHTSPECK_MESSAGE_FLS_H
